spring: 
  profiles: 
    active: 
    - dev
---
server:
  port: 8001

spring:
  application:
  profiles: dev
    name: pringcloud-config-dept-client
  data:
    mongodb:
      uri: mongodb://localhost:27017/test?authSource=admin
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-server-provider-dept-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: atguigu-microservicecloud
  company.name: www.leslie.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001

spring:
  application:
  profiles: test
    name: pringcloud-config-dept-client
  data:
    mongodb:
      uri: mongodb://localhost:27017/test2?authSource=admin
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-server-provider-dept-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: atguigu-microservicecloud
  company.name: www.leslie.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
