spring: 
  profiles: 
    active: 
    - dev
---
server: 
  port: 7001
spring: 
  profiles: dev
  application:
    name: springcloud-config-eureka-server
eureka: 
  client: 
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server: 
  port: 7001
spring: 
  profiles: test
  application:
    name: springcloud-config-eureka-server
eureka: 
  client: 
    register-with-eureka: false
    fetch-registry: false
    service-uri:
      defaultZone: http://eureka-test.com:7001/eureka/